"""
Endpoint metadata for GET /api/schema.

Manually maintained alongside actual endpoint definitions.
"""

SCHEMA = {
    "endpoints": [
        {
            "route": "/api/health",
            "method": "GET",
            "description": "Health check — confirms the API is running",
            "params": {},
            "auth": False,
        },
        {
            "route": "/api/schema",
            "method": "GET",
            "description": "Describes every endpoint in the API with params and types",
            "params": {},
            "auth": False,
        },
        {
            "route": "/api/modes",
            "method": "GET",
            "description": "Index of all exploration modes — returns id, name, and one-line description for each mode",
            "params": {},
            "auth": False,
        },
        {
            "route": "/api/modes/{mode_id}",
            "method": "GET",
            "description": "Full mode specification as plain text (Content-Type: text/plain). Used by Claude as procedural instructions for music exploration workflows.",
            "params": {
                "mode_id": {"type": "string", "required": True, "location": "path",
                            "enum": ["finish", "disco", "gap", "roots", "scene", "bridge", "adjacent", "mood", "cold", "revisit", "live", "festival", "canon-builder"]},
            },
            "auth": False,
        },
        {
            "route": "/api/session-start",
            "method": "GET",
            "description": "Combined session startup — returns listening state summary, mode suggestion, recent + top artists, tracked shows. Replaces 4-5 separate startup calls.",
            "params": {
                "format": {"type": "string", "required": False, "default": "compact", "enum": ["compact", "full"],
                           "description": "compact: pre-summarized text fields for minimal context usage. full: raw data objects."},
            },
            "auth": True,
        },
        {
            "route": "/api/summary",
            "method": "GET",
            "description": "High-level stats: total listens, unique tracks/artists, platform breakdown, album session stats (full/partial counts)",
            "params": {},
            "auth": True,
        },
        {
            "route": "/api/top-artists",
            "method": "GET",
            "description": "Top artists by listen count with album session counts (full/partial). Default compact format returns 'Artist (plays/Nt [Fs/Ps])' comma-separated plain text.",
            "params": {
                "start_date": {"type": "ISO date string", "required": False},
                "end_date": {"type": "ISO date string", "required": False},
                "days": {"type": "int", "required": False},
                "limit": {"type": "int", "required": False, "default": 10, "max": 1000},
                "format": {"type": "string", "required": False, "default": "compact", "enum": ["compact", "json"]},
            },
            "auth": True,
        },
        {
            "route": "/api/top-tracks",
            "method": "GET",
            "description": "Top tracks by listen count. Default compact format returns 'Artist - Title (plays)' comma-separated plain text.",
            "params": {
                "artist": {"type": "string", "required": False},
                "start_date": {"type": "ISO date string", "required": False},
                "end_date": {"type": "ISO date string", "required": False},
                "days": {"type": "int", "required": False},
                "limit": {"type": "int", "required": False, "default": 10, "max": 1000},
                "format": {"type": "string", "required": False, "default": "compact", "enum": ["compact", "json"]},
            },
            "auth": True,
        },
        {
            "route": "/api/top-albums",
            "method": "GET",
            "description": "Top albums by listen count with album session counts (full/partial). Default compact format returns 'Artist - Album (plays [Fs/Ps])' comma-separated plain text.",
            "params": {
                "artist": {"type": "string", "required": False},
                "start_date": {"type": "ISO date string", "required": False},
                "end_date": {"type": "ISO date string", "required": False},
                "days": {"type": "int", "required": False},
                "limit": {"type": "int", "required": False, "default": 10, "max": 1000},
                "format": {"type": "string", "required": False, "default": "compact", "enum": ["compact", "json"]},
            },
            "auth": True,
        },
        {
            "route": "/api/timeline",
            "method": "GET",
            "description": "Listen counts and album session counts (full/partial/total) over time at day/week/month/year granularity",
            "params": {
                "granularity": {"type": "string", "required": False, "default": "month", "enum": ["day", "week", "month", "year"]},
                "start_date": {"type": "ISO date string", "required": False},
                "end_date": {"type": "ISO date string", "required": False},
                "days": {"type": "int", "required": False},
            },
            "auth": True,
        },
        {
            "route": "/api/recent",
            "method": "GET",
            "description": "Most recent listens. Default compact format returns 'MMM DD HH:MM Artist - Track (Album)' one per line.",
            "params": {
                "limit": {"type": "int", "required": False, "default": 20, "max": 500},
                "format": {"type": "string", "required": False, "default": "compact", "enum": ["compact", "json"]},
            },
            "auth": True,
        },
        {
            "route": "/api/artist/{artist_name}",
            "method": "GET",
            "description": "Detailed stats for a specific artist: total listens, top tracks, yearly breakdown, session summary (full/partial counts), recent album sessions",
            "params": {
                "artist_name": {"type": "string", "required": True, "location": "path"},
            },
            "auth": True,
        },
        {
            "route": "/api/album-completion",
            "method": "GET",
            "description": "All-time tracklist coverage per album — counts how many distinct tracks have EVER been played, regardless of when. NOT time-sensitive: playing 1 track/month for a year counts the same as playing the whole album in one sitting. Use /api/album-sessions instead for actual full album listens in a single sitting.",
            "params": {
                "artist": {"type": "string", "required": False},
                "start_date": {"type": "ISO date string", "required": False},
                "end_date": {"type": "ISO date string", "required": False},
                "days": {"type": "int", "required": False},
                "min_completion": {"type": "float 0-1", "required": False},
                "max_completion": {"type": "float 0-1", "required": False},
                "limit": {"type": "int", "required": False, "default": 10, "max": 1000},
                "format": {"type": "string", "required": False, "default": "compact", "enum": ["compact", "json"]},
            },
            "auth": True,
        },
        {
            "route": "/api/album-sessions",
            "method": "GET",
            "description": "Album listening sessions — times the user sat down and played through an album in one sitting (precomputed, gap-based detection). Use session_type=full for complete album listens. THIS is the correct endpoint for 'albums listened to all the way through', 'most replayed albums', 'have I finished this album', etc. Prefer this over /api/album-completion for any question about album listening behavior.",
            "params": {
                "artist": {"type": "string", "required": False},
                "album": {"type": "string", "required": False},
                "start_date": {"type": "ISO date string", "required": False},
                "end_date": {"type": "ISO date string", "required": False},
                "days": {"type": "int", "required": False},
                "min_completion": {"type": "float 0-1", "required": False, "default": 0.0},
                "session_type": {"type": "string", "required": False, "enum": ["full", "partial"]},
                "release_type": {"type": "string", "required": False, "enum": ["Album", "EP", "Single"], "description": "Filter by MusicBrainz release type"},
                "limit": {"type": "int", "required": False, "default": 50, "max": 1000},
            },
            "auth": True,
        },
        {
            "route": "/api/album-sessions/stats",
            "method": "GET",
            "description": "Aggregate album session stats: total full/partial sessions, by-year breakdown, top 25 most-replayed albums. Best endpoint for 'what albums do I listen to most' and 'how many albums have I finished'.",
            "params": {
                "start_date": {"type": "ISO date string", "required": False},
                "end_date": {"type": "ISO date string", "required": False},
                "days": {"type": "int", "required": False},
                "session_type": {"type": "string", "required": False, "enum": ["full", "partial"]},
                "release_type": {"type": "string", "required": False, "enum": ["Album", "EP", "Single"], "description": "Filter by MusicBrainz release type"},
            },
            "auth": True,
        },
        {
            "route": "/api/artists/batch",
            "method": "POST",
            "description": "Bulk artist lookup with album completion and session data",
            "body": {"artists": ["list of artist names"]},
            "auth": True,
        },
        {
            "route": "/api/album-tracklist-resolver",
            "method": "POST",
            "description": "Trigger MusicBrainz resolution for albums missing tracklist data",
            "body": {"artist": "optional string", "album": "optional string"},
            "auth": True,
        },
        {
            "route": "/api/album-tracklist-resolver",
            "method": "GET",
            "description": "Check album tracklist resolution status",
            "params": {},
            "auth": True,
        },
        {
            "route": "/api/query",
            "method": "POST",
            "description": "Run an arbitrary read-only SQL query (uses read-only DB role)",
            "body": {"sql": "SELECT ...", "limit": 100},
            "auth": True,
        },
        {
            "route": "/api/chicago-shows",
            "method": "GET",
            "description": "Upcoming Chicago concerts and festival lineups. Default compact format returns one show per line.",
            "params": {
                "start_date": {"type": "ISO date string", "required": False, "default": "today"},
                "end_date": {"type": "ISO date string", "required": False},
                "days": {"type": "int", "required": False},
                "venue": {"type": "string", "required": False, "description": "Fuzzy match venue name"},
                "artist": {"type": "string", "required": False, "description": "Fuzzy match artist name"},
                "genre": {"type": "string", "required": False, "description": "Filter by Last.fm genre tag (e.g. 'post-punk', 'indie rock', 'hip-hop')"},
                "festival": {"type": "string", "required": False, "description": "Filter by festival name — fuzzy match (e.g. 'lolla', 'arc', 'Riot Fest')"},
                "status": {"type": "string", "required": False, "default": "upcoming", "enum": ["upcoming", "sold_out", "cancelled", "past", "all"]},
                "limit": {"type": "int", "required": False, "default": 20, "max": 1000},
                "format": {"type": "string", "required": False, "default": "compact", "enum": ["compact", "json"]},
            },
            "auth": True,
        },
        {
            "route": "/api/chicago-shows/presales",
            "method": "GET",
            "description": "Upcoming presales sorted by presale start date (Ticketmaster-sourced shows only)",
            "params": {
                "days": {"type": "int", "required": False, "default": 14, "description": "Presales starting within N days"},
                "limit": {"type": "int", "required": False, "default": 50, "max": 1000},
            },
            "auth": True,
        },
        {
            "route": "/api/chicago-shows/just-announced",
            "method": "GET",
            "description": "Shows first seen in the last N days — new listings across all sources",
            "params": {
                "days": {"type": "int", "required": False, "default": 7},
                "limit": {"type": "int", "required": False, "default": 50, "max": 1000},
            },
            "auth": True,
        },
        {
            "route": "/api/chicago-shows/match",
            "method": "GET",
            "description": "Cross-reference upcoming shows against listening history — ranked by relevance score. Default compact format returns one match per line with flags.",
            "params": {
                "start_date": {"type": "ISO date string", "required": False, "default": "today"},
                "end_date": {"type": "ISO date string", "required": False, "default": "+90 days"},
                "days": {"type": "int", "required": False},
                "min_listens": {"type": "int", "required": False, "default": 1, "description": "Minimum lifetime listens to qualify as a match"},
                "genre": {"type": "string", "required": False, "description": "Filter matched shows by Last.fm genre tag"},
                "festival": {"type": "string", "required": False, "description": "Filter by festival name — fuzzy match (e.g. 'lolla', 'arc', 'Riot Fest')"},
                "limit": {"type": "int", "required": False, "default": 15, "max": 1000},
                "format": {"type": "string", "required": False, "default": "compact", "enum": ["compact", "json"]},
            },
            "auth": True,
        },
        {
            "route": "/api/discover",
            "method": "GET",
            "description": "Discover similar artists to a seed artist. Default compact format returns one artist per line with similarity, tags, and show info.",
            "params": {
                "seed": {"type": "string", "required": True, "description": "Seed artist name"},
                "include_events": {"type": "bool", "required": False, "default": True, "description": "Include upcoming Chicago shows for similar artists"},
                "max_similar": {"type": "int", "required": False, "default": 15, "max": 100},
                "exclude_heard": {"type": "bool", "required": False, "default": False, "description": "Filter out artists you've already listened to"},
                "genre": {"type": "string", "required": False, "description": "Filter similar artists by Last.fm genre tag"},
                "format": {"type": "string", "required": False, "default": "compact", "enum": ["compact", "json"]},
            },
            "auth": True,
        },
        {
            "route": "/api/chicago-shows/interest",
            "method": "PUT",
            "description": "Set or update interest status for a show. Upserts — call again to change your mind.",
            "body": {
                "show_id": {"type": "int", "required": True, "description": "The show_id from chicago_shows"},
                "status": {"type": "string", "required": True, "enum": ["going", "interested", "not_interested", "cant_afford"]},
                "note": {"type": "string", "required": False, "description": "Free-text note (e.g. 'too expensive', 'love their new album')"},
            },
            "auth": True,
        },
        {
            "route": "/api/chicago-shows/interest",
            "method": "GET",
            "description": "List all shows you've tracked interest in. Includes full show data and travel times.",
            "params": {
                "status": {"type": "string", "required": False, "description": "Filter by interest status", "enum": ["going", "interested", "not_interested", "cant_afford"]},
                "limit": {"type": "int", "required": False, "default": 50, "max": 1000},
            },
            "auth": True,
        },
        {
            "route": "/api/chicago-shows/interest/{show_id}",
            "method": "DELETE",
            "description": "Remove interest tracking for a show.",
            "auth": True,
        },
        {
            "route": "/api/canonical",
            "method": "POST",
            "description": "Upsert canonical albums. Batch support — send multiple albums per request. ON CONFLICT updates existing entries.",
            "body": {
                "albums": [{"artist": "string", "album": "string", "year": "int (optional)",
                            "genre": "string", "subgenre": "string (optional)",
                            "tier": "essential|important|deep (default: essential)",
                            "description": "string (optional)"}],
            },
            "auth": True,
        },
        {
            "route": "/api/canonical",
            "method": "GET",
            "description": "List canonical albums. Default compact format returns one album per line with genre, tier, and description.",
            "params": {
                "genre": {"type": "string", "required": False, "description": "Filter by genre (case-insensitive)"},
                "subgenre": {"type": "string", "required": False, "description": "Filter by subgenre (case-insensitive)"},
                "tier": {"type": "string", "required": False, "enum": ["essential", "important", "deep"]},
                "artist": {"type": "string", "required": False, "description": "Fuzzy match artist name"},
                "limit": {"type": "int", "required": False, "default": 50, "max": 1000},
                "offset": {"type": "int", "required": False, "default": 0},
                "format": {"type": "string", "required": False, "default": "compact", "enum": ["compact", "json"]},
            },
            "auth": True,
        },
        {
            "route": "/api/canonical/gaps",
            "method": "GET",
            "description": "Coverage report: joins canonical albums against listening history to show heard/unheard status with play counts, dates, and album session counts (full/partial).",
            "params": {
                "genre": {"type": "string", "required": False, "description": "Filter by genre (case-insensitive)"},
                "subgenre": {"type": "string", "required": False, "description": "Filter by subgenre (case-insensitive)"},
                "tier": {"type": "string", "required": False, "enum": ["essential", "important", "deep"]},
                "heard": {"type": "string", "required": False, "enum": ["true", "false"],
                          "description": "Filter: true = only heard albums, false = only unheard, omit = all"},
                "limit": {"type": "int", "required": False, "default": 100, "max": 1000},
                "offset": {"type": "int", "required": False, "default": 0},
                "format": {"type": "string", "required": False, "default": "compact", "enum": ["compact", "json"]},
            },
            "auth": True,
        },
        {
            "route": "/api/canonical/{album_id}",
            "method": "DELETE",
            "description": "Delete a canonical album by ID.",
            "params": {
                "album_id": {"type": "int", "required": True, "location": "path"},
            },
            "auth": True,
        },
        {
            "route": "/api/canonical",
            "method": "DELETE",
            "description": "Delete a canonical album by artist + album name match (case-insensitive).",
            "params": {
                "artist": {"type": "string", "required": True},
                "album": {"type": "string", "required": True},
            },
            "auth": True,
        },
    ]
}
