"""
Endpoint metadata for GET /api/schema.

Manually maintained alongside actual endpoint definitions.
"""

SCHEMA = {
    "endpoints": [
        {
            "route": "/api/health",
            "method": "GET",
            "description": "Health check — confirms the API is running",
            "params": {},
            "auth": False,
        },
        {
            "route": "/api/schema",
            "method": "GET",
            "description": "Describes every endpoint in the API with params and types",
            "params": {},
            "auth": False,
        },
        {
            "route": "/api/summary",
            "method": "GET",
            "description": "High-level stats: total listens, unique tracks/artists, platform breakdown",
            "params": {},
            "auth": True,
        },
        {
            "route": "/api/top-artists",
            "method": "GET",
            "description": "Top artists by listen count",
            "params": {
                "start_date": {"type": "ISO date string", "required": False},
                "end_date": {"type": "ISO date string", "required": False},
                "days": {"type": "int", "required": False},
                "limit": {"type": "int", "required": False, "default": 50, "max": 1000},
            },
            "auth": True,
        },
        {
            "route": "/api/top-tracks",
            "method": "GET",
            "description": "Top tracks by listen count",
            "params": {
                "artist": {"type": "string", "required": False},
                "start_date": {"type": "ISO date string", "required": False},
                "end_date": {"type": "ISO date string", "required": False},
                "days": {"type": "int", "required": False},
                "limit": {"type": "int", "required": False, "default": 50, "max": 1000},
            },
            "auth": True,
        },
        {
            "route": "/api/top-albums",
            "method": "GET",
            "description": "Top albums by listen count",
            "params": {
                "artist": {"type": "string", "required": False},
                "start_date": {"type": "ISO date string", "required": False},
                "end_date": {"type": "ISO date string", "required": False},
                "days": {"type": "int", "required": False},
                "limit": {"type": "int", "required": False, "default": 50, "max": 1000},
            },
            "auth": True,
        },
        {
            "route": "/api/timeline",
            "method": "GET",
            "description": "Listen counts over time at day/week/month/year granularity",
            "params": {
                "granularity": {"type": "string", "required": False, "default": "month", "enum": ["day", "week", "month", "year"]},
                "start_date": {"type": "ISO date string", "required": False},
                "end_date": {"type": "ISO date string", "required": False},
                "days": {"type": "int", "required": False},
            },
            "auth": True,
        },
        {
            "route": "/api/recent",
            "method": "GET",
            "description": "Most recent listens",
            "params": {
                "limit": {"type": "int", "required": False, "default": 50, "max": 500},
            },
            "auth": True,
        },
        {
            "route": "/api/artist/{artist_name}",
            "method": "GET",
            "description": "Detailed stats for a specific artist: total listens, top tracks, yearly breakdown",
            "params": {
                "artist_name": {"type": "string", "required": True, "location": "path"},
            },
            "auth": True,
        },
        {
            "route": "/api/album-completion",
            "method": "GET",
            "description": "Lifetime tracklist coverage per album — how many tracks you've heard",
            "params": {
                "artist": {"type": "string", "required": False},
                "start_date": {"type": "ISO date string", "required": False},
                "end_date": {"type": "ISO date string", "required": False},
                "days": {"type": "int", "required": False},
                "min_completion": {"type": "float 0-1", "required": False},
                "max_completion": {"type": "float 0-1", "required": False},
                "limit": {"type": "int", "required": False, "default": 50, "max": 1000},
            },
            "auth": True,
        },
        {
            "route": "/api/album-sessions",
            "method": "GET",
            "description": "Detected full and partial album listening sessions (precomputed)",
            "params": {
                "artist": {"type": "string", "required": False},
                "album": {"type": "string", "required": False},
                "start_date": {"type": "ISO date string", "required": False},
                "end_date": {"type": "ISO date string", "required": False},
                "days": {"type": "int", "required": False},
                "min_completion": {"type": "float 0-1", "required": False, "default": 0.0},
                "session_type": {"type": "string", "required": False, "enum": ["full", "partial"]},
                "release_type": {"type": "string", "required": False, "enum": ["Album", "EP", "Single"], "description": "Filter by MusicBrainz release type"},
                "limit": {"type": "int", "required": False, "default": 50, "max": 1000},
            },
            "auth": True,
        },
        {
            "route": "/api/album-sessions/stats",
            "method": "GET",
            "description": "Aggregate session stats: totals, by-year breakdown, top 25 albums by full sessions",
            "params": {
                "start_date": {"type": "ISO date string", "required": False},
                "end_date": {"type": "ISO date string", "required": False},
                "days": {"type": "int", "required": False},
                "session_type": {"type": "string", "required": False, "enum": ["full", "partial"]},
                "release_type": {"type": "string", "required": False, "enum": ["Album", "EP", "Single"], "description": "Filter by MusicBrainz release type"},
            },
            "auth": True,
        },
        {
            "route": "/api/artists/batch",
            "method": "POST",
            "description": "Bulk artist lookup with album completion and session data",
            "body": {"artists": ["list of artist names"]},
            "auth": True,
        },
        {
            "route": "/api/album-tracklist-resolver",
            "method": "POST",
            "description": "Trigger MusicBrainz resolution for albums missing tracklist data",
            "body": {"artist": "optional string", "album": "optional string"},
            "auth": True,
        },
        {
            "route": "/api/album-tracklist-resolver",
            "method": "GET",
            "description": "Check album tracklist resolution status",
            "params": {},
            "auth": True,
        },
        {
            "route": "/api/query",
            "method": "POST",
            "description": "Run an arbitrary read-only SQL query (uses read-only DB role)",
            "body": {"sql": "SELECT ...", "limit": 100},
            "auth": True,
        },
        {
            "route": "/api/chicago-shows",
            "method": "GET",
            "description": "Upcoming Chicago concerts — query by date range, venue, artist. Trigram fuzzy matching on artist/venue names.",
            "params": {
                "start_date": {"type": "ISO date string", "required": False, "default": "today"},
                "end_date": {"type": "ISO date string", "required": False},
                "days": {"type": "int", "required": False},
                "venue": {"type": "string", "required": False, "description": "Fuzzy match venue name"},
                "artist": {"type": "string", "required": False, "description": "Fuzzy match artist name"},
                "status": {"type": "string", "required": False, "default": "upcoming", "enum": ["upcoming", "sold_out", "cancelled", "past", "all"]},
                "limit": {"type": "int", "required": False, "default": 50, "max": 1000},
            },
            "auth": True,
        },
        {
            "route": "/api/chicago-shows/presales",
            "method": "GET",
            "description": "Upcoming presales sorted by presale start date (Ticketmaster-sourced shows only)",
            "params": {
                "days": {"type": "int", "required": False, "default": 14, "description": "Presales starting within N days"},
                "limit": {"type": "int", "required": False, "default": 50, "max": 1000},
            },
            "auth": True,
        },
        {
            "route": "/api/chicago-shows/just-announced",
            "method": "GET",
            "description": "Shows first seen in the last N days — new listings across all sources",
            "params": {
                "days": {"type": "int", "required": False, "default": 7},
                "limit": {"type": "int", "required": False, "default": 50, "max": 1000},
            },
            "auth": True,
        },
        {
            "route": "/api/chicago-shows/match",
            "method": "GET",
            "description": "Cross-reference upcoming shows against listening history — ranked by relevance score (log(listens) * track breadth * recency). The key endpoint for taste-based show recommendations.",
            "params": {
                "start_date": {"type": "ISO date string", "required": False, "default": "today"},
                "end_date": {"type": "ISO date string", "required": False, "default": "+90 days"},
                "days": {"type": "int", "required": False},
                "min_listens": {"type": "int", "required": False, "default": 1, "description": "Minimum lifetime listens to qualify as a match"},
                "limit": {"type": "int", "required": False, "default": 50, "max": 1000},
            },
            "auth": True,
        },
        {
            "route": "/api/discover",
            "method": "GET",
            "description": "Discover similar artists to a seed artist. Returns similarity scores, listening stats, genre tags, and upcoming Chicago shows. Powered by ListenBrainz similarity + Last.fm tags.",
            "params": {
                "seed": {"type": "string", "required": True, "description": "Seed artist name"},
                "include_events": {"type": "bool", "required": False, "default": True, "description": "Include upcoming Chicago shows for similar artists"},
                "max_similar": {"type": "int", "required": False, "default": 20, "max": 100},
                "exclude_heard": {"type": "bool", "required": False, "default": False, "description": "Filter out artists you've already listened to"},
            },
            "auth": True,
        },
    ]
}
